import {
  IconBrandAirbnb,
  IconBuildingSkyscraper,
  IconMail,
  IconBrandWhatsapp,
  IconMapPin,
  IconWorldWww,
  IconZoomQuestion,
  IconBrandFacebook,
  IconBrandInstagram,
  IconWifi,
  IconBrandNetflix,
  IconParkingCircle,
  IconWheelchair,
  IconBrandYoutube,
  IconTeapot,
  IconAirConditioningDisabled,
  IconSunElectricity,
  IconPropeller,
  IconShare,
} from "@tabler/icons-react";

export {
  IconBrandAirbnb,
  IconBuildingSkyscraper,
  IconMail,
  IconBrandWhatsapp,
  IconMapPin,
  IconWorldWww,
  IconZoomQuestion,
  IconBrandFacebook,
  IconBrandInstagram,
  IconWifi,
  IconBrandNetflix,
  IconParkingCircle,
  IconWheelchair,
  IconBrandYoutube,
  IconTeapot,
  IconAirConditioningDisabled,
  IconSunElectricity,
  IconPropeller,
  IconShare,
};
