import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import { ThemeProvider, ConvexProviderWithClerk } from "../../providers";
import { ClerkProvider } from "@clerk/nextjs";
import { shadcn } from "@clerk/themes";
import { esES, enUS } from '@clerk/localizations'

import { ModeToggle } from "@/components/features";
import "./globals.css";
import { i18n, Locale } from "@/i18n-config";

const poppinsSans = Poppins({
  variable: "--font-poppins-sans",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
}>) {
  const { lang } = await params;
  return (
    <html lang={lang} suppressHydrationWarning>
      <body
        className={`${poppinsSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider
          localization={lang === 'en' ? enUS : esES}
          appearance={{
            baseTheme: shadcn,
            variables: {
              fontFamily: "var(--font-poppins-sans)",
            },
            layout: {
              logoPlacement: "outside",
            },
          }}
        >
          <ConvexProviderWithClerk>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <ModeToggle />
              {children}
            </ThemeProvider>
          </ConvexProviderWithClerk>
        </ClerkProvider>
      </body>
    </html>
  );
}
